name: notes_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_slidable: ^3.0.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  meta: ^1.9.1
  test: ^1.24.3
  flutter_test:
    sdk: flutter
  uuid: ^4.1.0
  lottie: ^2.7.0
  bloc_test: ^9.1.5
  shared_preferences: ^2.2.2
  mocktail: ^1.0.1

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/json/
    - assets/screenshots/

  fonts:
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Bold.ttf
        - asset: assets/fonts/Merriweather-Italic.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-bold.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf

flutter_icons:
  andrdoid: true
  ios: true
  image_path: "assets/icons/note-icon.png"
